/* Pack the three chosen hearth plates into WebP data URIs.
 *
 * No sharp on this machine, so the resize + encode runs in the headless Chrome
 * that is already here for screenshots — canvas drawImage + toDataURL('image/webp').
 *
 * Size is the whole point. cindervale.html is already ~3.4MB and the Electron
 * wrapper aborts its fetch at 6s, so anything that lands in the file has to
 * justify its bytes; the target here is well under 30KB per plate. A radial
 * alpha mask is baked in so the art dies into the panel's own black instead of
 * ending on a rectangle edge.
 */
const path = require('path'), fs = require('fs');
const KIT = 'C:/Users/Jordan/Desktop/cindervale-trailer-kit';
const puppeteer = require(path.join(KIT, 'node_modules/puppeteer-core'));
const CHROME = path.join(KIT, 'browsers/chrome/win64-151.0.7922.71/chrome-win64/chrome.exe');

const SRC = path.join(__dirname, 'fire');
const PICK = [
  { id: 'burning', file: 'burn-2.png' },
  { id: 'banked',  file: 'bank-1.png' },
  { id: 'cold',    file: 'cold-2.png' },
];
/* 472x400 = 2x the 236x200 plate, so it stays clean on a scaled-up UI. */
const W = 472, H = 400;

(async () => {
  const b = await puppeteer.launch({ executablePath: CHROME, headless: true,
    args: ['--allow-file-access-from-files'] });
  const p = await b.newPage();
  await p.goto('data:text/html,<body>');

  const out = {};
  for (const j of PICK) {
    const raw = fs.readFileSync(path.join(SRC, j.file)).toString('base64');
    for (const q of [0.62, 0.72, 0.82]) {
      const uri = await p.evaluate(async (raw, W, H, q) => {
        const img = new Image();
        img.src = 'data:image/png;base64,' + raw;
        await img.decode();
        const c = document.createElement('canvas');
        c.width = W; c.height = H;
        const x = c.getContext('2d');
        // cover-crop to the plate's aspect
        const s = Math.max(W / img.width, H / img.height);
        const dw = img.width * s, dh = img.height * s;
        x.drawImage(img, (W - dw) / 2, (H - dh) / 2, dw, dh);
        // feather the edges so the plate has no visible seam against the panel
        x.globalCompositeOperation = 'destination-in';
        const g = x.createRadialGradient(W / 2, H * 0.56, Math.min(W, H) * 0.20,
                                         W / 2, H * 0.56, Math.max(W, H) * 0.62);
        g.addColorStop(0, 'rgba(0,0,0,1)');
        g.addColorStop(0.66, 'rgba(0,0,0,0.96)');
        g.addColorStop(1, 'rgba(0,0,0,0)');
        x.fillStyle = g; x.fillRect(0, 0, W, H);
        return c.toDataURL('image/webp', q);
      }, raw, W, H, q);
      const kb = Math.round(uri.length * 0.75 / 1024);
      console.log('  ' + j.id + '  q' + q + '  ' + kb + 'KB');
      if (!out[j.id] || q === 0.72) out[j.id] = uri;   // 0.72 is the shipped pick
    }
  }
  await b.close();

  fs.writeFileSync(path.join(__dirname, 'fire-plates.js'),
    '/* Generated by packfire.js — three hearth states as WebP data URIs. */\n'
    + 'window.CK_FIRE=' + JSON.stringify(out) + ';\n');
  const total = Object.values(out).reduce((a, s) => a + s.length * 0.75, 0);
  console.log('fire-plates.js written · ' + Math.round(total / 1024) + 'KB of image data total');
})().catch(e => { console.error(e); process.exit(1); });
