/* Splice the painted achievement emblems into the game as ICONS entries.
 *
 *     node _iconart/injectach.js --pack pack_ach.json
 *
 * Each achievement's `icon` field is its own id, so ICONS[<id>] has to exist or
 * iconHTML() returns the id VERBATIM and the card shows the literal text
 * "first_swing". That failure is silent, which is why this asserts coverage at
 * the end rather than trusting the count.
 *
 * MERGES, like injectnodes.js: ICONS is built by the game itself and has no sheet
 * on disk to rebuild from, so a replace would wipe every item and monster icon.
 * Re-running replaces its own block instead of stacking.
 */
'use strict';
const fs = require('fs'), path = require('path');
const arg = k => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : null; };
const PACK = arg('--pack') || path.join(__dirname, 'pack_ach.json');
const FILE = arg('--in') || path.join(__dirname, '..', 'cindervale.html');

const pack = JSON.parse(fs.readFileSync(path.resolve(PACK), 'utf8'));
let html = fs.readFileSync(FILE, 'utf8');

const START = '/* ==== ACH_ART (generated by _iconart/injectach.js) ==== */';
const END = '/* ==== /ACH_ART ==== */';

const body = Object.entries(pack)
  .map(([id, uri]) => '  ICONS[' + JSON.stringify(id) + ']=' + JSON.stringify(
    '<img class="ev-icon art-ach" alt="" loading="lazy" src="' + uri + '">') + ';')
  .join('\n');
const block = START + '\n(function(){\n' + body + '\n})();\n' + END;

const old = html.indexOf(START);
if (old >= 0) {
  const e = html.indexOf(END, old);
  html = html.slice(0, old) + block + html.slice(e + END.length);
  console.log('replaced the existing ACH_ART block');
} else {
  /* Must land AFTER the achievements are declared, so anchor on ACH_BY_ID. */
  const anchor = 'const ACH_BY_ID={}; ACHIEVEMENTS.forEach(a=>{ ACH_BY_ID[a.id]=a; });';
  if (html.indexOf(anchor) < 0) { console.error('anchor not found'); process.exit(1); }
  html = html.replace(anchor, anchor + '\n' + block);
  console.log('inserted a new ACH_ART block after ACH_BY_ID');
}
fs.writeFileSync(FILE, html);
console.log('ACH_ART: ' + Object.keys(pack).length + ' emblems, file now ' +
  (Buffer.byteLength(html) / 1048576).toFixed(2) + ' MB');
