/* Splice the item art into the game as ICONS overrides.
 *
 *     node _iconart/inject.js                    pack.json -> cindervale.html (in place)
 *     node _iconart/inject.js --pack p.json --in a.html --out b.html
 *     node _iconart/inject.js --remove           take the pack back out
 *
 * Every render site funnels through iconHTML(id), which returns ICONS[id] verbatim,
 * so replacing an inline SVG string with an <img> string needs no change at any
 * call site. This is the same mechanism the monster ART_MON and pet ART_PET packs
 * already use — an id not in the pack simply keeps its SVG, so a partial art pass
 * still boots.
 *
 * Idempotent: re-running replaces the previous block instead of stacking, which is
 * what makes "regenerate one family and re-inject" safe to do repeatedly.
 */
'use strict';
const fs = require('fs'), path = require('path');

const arg = k => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : null; };
const has = k => process.argv.includes(k);

const PACK = arg('--pack') || path.join(__dirname, 'pack.json');
const IN   = arg('--in')  || path.join(__dirname, '..', 'cindervale.html');
const OUT  = arg('--out') || IN;

const OPEN = '/* ==ITEM-ART-START== */', CLOSE = '/* ==ITEM-ART-END== */';
/* Land it right after the monster pack, which is already positioned after ICONS
   exists. Anchoring to the monster pack's own end marker means this cannot drift
   above the ICONS definition however the file moves around it. */
const ANCHOR = '/* ==ART-PACK-END== */';
const CSS_MARK = '.ev-icon.art-item{';

let s = fs.readFileSync(IN, 'utf8');

// always drop any previous block first
const a = s.indexOf(OPEN), b = s.indexOf(CLOSE);
if (a >= 0 && b > a) s = s.slice(0, a) + s.slice(b + CLOSE.length);

if (has('--remove')) {
  s = s.replace(new RegExp('\\n\\.ev-icon\\.art-item\\{[^}]*\\}', 'g'), '');
  fs.writeFileSync(OUT, s);
  console.log('item art pack removed from ' + path.basename(OUT));
  process.exit(0);
}

const pack = JSON.parse(fs.readFileSync(PACK, 'utf8'));
const ids = Object.keys(pack).sort();
if (!ids.length) throw new Error('pack is empty');

const entries = ids.map(id => JSON.stringify(id) + ':' + JSON.stringify(
  '<img class="ev-icon art-item" alt="" loading="lazy" src="' + pack[id] + '">')).join(',\n');

const BLOCK = `
${OPEN}
/* Painted item art (skilling materials). Overrides the inline-SVG ICONS entry for
   each id it names; anything not in here keeps its SVG, so a partial pass boots.
   Sized by .ev-icon (1em from the parent font-size) exactly like the SVGs were —
   which is why these are drawn for a 15px satchel tile, not for this listing.
   Generated by _iconart/; re-run gen -> key -> pack -> inject to replace. */
(function(){
  var ART_ITEM={
${entries}
  };
  for(var k in ART_ITEM){ if(typeof ICONS!=='undefined') ICONS[k]=ART_ITEM[k]; }
})();
${CLOSE}
`;

if (!s.includes(ANCHOR)) throw new Error('anchor not found: ' + ANCHOR);
s = s.replace(ANCHOR, ANCHOR + '\n' + BLOCK);

if (!s.includes(CSS_MARK)) {
  const CSS = '\n/* Item art sits where an SVG used to: contained, and centred on the text baseline. */\n'
    + '.ev-icon.art-item{object-fit:contain;image-rendering:auto;vertical-align:middle}\n';
  const last = s.lastIndexOf('</style>');
  if (last < 0) throw new Error('no </style> to attach the rule to');
  s = s.slice(0, last) + CSS + s.slice(last);
}

fs.writeFileSync(OUT, s);
const kb = n => (n / 1024).toFixed(0) + ' KB';
console.log('injected ' + ids.length + ' item icons into ' + path.basename(OUT));
console.log('  block ' + kb(BLOCK.length) + ', file now ' + (fs.statSync(OUT).size / 1048576).toFixed(2) + ' MB');
